before_script:
  - hostname
  - whoami
  - sudo docker --version
  - pwd; ls -la


stages:
  - build
  - deploy_staging
  - deploy

build:
  tags: 
    - IBIEM
    - ipyn-az-09r
  stage: build
  script: 
    - echo "Building the app in staging"
    - ./build-test
    - ./regression-test

deploy_staging:
  tags: 
    - IBIEM
    - ipyn-az-09r
  stage: deploy
  script:
    - echo "Building the app in staging"
    - ./build-test
    - echo "Deploy to staging server"
    - ./run-test-instance
  environment:
    name: staging
  only:
  - staging


deploy_production:
  tags: 
    - IBIEM
    - ipyn-az-09r
  stage: deploy
  script:
    - echo "Building the production app"
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master


